---
output:
  html_document
---

<br>

<h5>
I study how to bring health services closer to the people who need them. My work spans the continuum from formative studies that use design thinking approaches to create new services, to large scale randomized controlled trials to estimate the impact of interventions.
</h5>

<br>

# Family Planning

I co-founded a digital health company called [Nivi](https://www.nivi.io/) and serve as the company's Chief Scientist. Nivi’s vision is to be the most trusted source of information about women’s health. Launched in 2016, Nivi’s core product is the first digital contraceptive screening and referral service in East Africa. Anyone with a basic mobile phone can complete a free screening, receive personalized recommendations for contraceptive methods, referrals to nearby healthcare providers, and provide feedback on their experience with providers and methods. Nivi is unique in its ability to use data on women’s contraceptive preferences and behavior to bring efficiency and transparency to family planning markets, help women to make informed choices, and give healthcare providers, governments, and industry new insights and tools for advancing public health and engaging consumers on a more personal level. Nivi is easy to use, private, and free.

# Perinatal Depression

Depression is a leading cause of disability worldwide, and women suffering from perinatal depression are a particularly underserved population. Depression during pregnancy and in the postpartum period is associated with a number poor outcomes for women and their children, including increased maternal morbidity and mortality, poor infant health, and poor early childhood outcomes. While effective interventions exist for common mental disorders that occur during pregnancy and the postpartum period, most cases in low- and middle-income countries go untreated. We are trying to change that by creating better screening tools and developing entirely new treatment delivery channels that have the potential for a step change in expanding access to care.

* [Developing and validating a perinatal depression screening tool in Kenya blending Western criteria with local idioms: A mixed methods study](https://urldefense.proofpoint.com/v2/url?u=https-3A__authors.elsevier.com_a_1WBWy-5F3m9tfYnN&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=Xnx2OUnha37evUh4dXebwfOFyRdFP6E6dmaGsqPyeqs&m=tJX-6xxmamRc5GPfQIRWMBbTj6DpGVKssgYBN_oV1z8&s=vYKJbED3_6bu0Lm5mr9n3ZQF-3ECalXF4GUwKujtJfQ&e=) (2018) with Hawa Tuli, Edith Kwobah, Diana Menya, Irene Chesire, and Christina Schmidt, *Journal of Affective Disorders* ([surveys, data, and full replication materials](https://ericpgreen.github.io/pdeps))

# Poverty and Mental Health

What is the relationship between poverty and mental illness? Do interventions intended to alleviate poverty have indirect effects on mental health? I began studying these questions in 2009 with [Chris Blattman](https://chrisblattman.com/), [Jeannie Annan](http://jeannieannan.com/), and [Julian Jamison](https://www.linkedin.com/in/julian-jamison-733b36/). We partnered with [AVSI](https://www.avsi.org/en/), an Italian development agency with deep roots in Uganda, to conduct a 3-year cluster randomized trial of skills training and cash transfer program called WINGS.

* [The returns to microenterprise support among the ultra-poor: A field experiment in post-war Uganda](https://www.researchgate.net/profile/Eric_Green5/publication/299501234_The_Returns_to_Microenterprise_Support_Among_the_Ultra-poor_A_Field_Experiment_in_Post-war_Uganda/links/570cd2b608ae2b772e41ef56/The-Returns-to-Microenterprise-Support-Among-the-Ultra-poor-A-Field-Experiment-in-Post-war-Uganda.pdf?_iepl%5BhomeFeedViewId%5D=MoAUZMqV1rb0eITidsjnMZAv&_iepl%5Bcontexts%5D%5B0%5D=pcfhf&_iepl%5BinteractionType%5D=publicationDownload&origin=publication_detail&ev=pub_int_prw_xdl&msrp=8PQGqcj6OXlfVR5BAKxq7dmAS4gLCdPljhC8A59WHIlTL1OQ1_WAZ3EvDC1DvhYfAmCsZql_3AdhKmbLSs2C9pMR-fKl5T-9refMh0a6T3ew5PXxlqqdRySS.LPx4xXWn9_qvU9FfxOtQJY7znkFi46ekz6NH7PQplMJ4GfM6gwXBfHUI3E1zMKDiFhlRMs1v-8q4pDJutHz3sJB-Gk4c54v9inq0UQ.RL4CemZWu8g6_Kq2-ZGm6gmFjp8uK49jet8pPCgnJkwuGnftJTEL4ksIqIEhn452x4hOhOswLUj2u54HNmei11YkjK0Fu7a8xD3HYQ.OlqJA5LnVoBZJKMs5r5v9txzrCLUcTdi-V3cjqNe0qGe9FQreMR4cORd1BSFq8YMNORgeNNCZT8XT4QA29fzaaFfeN9ywpqVbW6oZg) (2016) with Christopher Blattman, Julian Jamison, and Jeannie Annan, *American Economic Journal: Applied Economics* ([surveys, data, and full replication materials](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/QA0R1O))

* [Does poverty alleviation decrease depression symptoms in post-conflict settings? A cluster-randomized trial of microenterprise assistance in northern Uganda](https://www.researchgate.net/profile/Julian_Jamison/publication/296478618_Does_poverty_alleviation_decrease_depression_symptoms_in_post-conflict_settings_A_cluster-randomized_trial_of_microenterprise_assistance_in_Northern_Uganda/links/5706e51208aefb22b0934873/Does-poverty-alleviation-decrease-depression-symptoms-in-post-conflict-settings-A-cluster-randomized-trial-of-microenterprise-assistance-in-Northern-Uganda.pdf?_iepl%5BhomeFeedViewId%5D=dbTbUBcGwY8bM5Vcfc5dmUUj&_iepl%5Bcontexts%5D%5B0%5D=pcfhf&_iepl%5BinteractionType%5D=publicationDownload&origin=publication_detail&ev=pub_int_prw_xdl&msrp=2oifQnVl3yBbPOHQO3ixWHE9PnSfZTQUXDn_Htr9H82bLqsqWoL9RksxECv8N3Zv8ctkNdRQhUwcZWTPPMQMArKdq-1K_JxNE1_rr4GYirQZyJmNp310PZlC.sBOLf6GLJrjCbS7mBJKh8SR3G671x0AolscCR_0RpqAxdrFrayQ-OT4riirT8inB74YTXBCRFgfPMnXk3g1Qe4oHjBTdxjxz1KSfzw.Nl2iBCSOD5jsL3xwEkx0PNf4Ou57jxouoGUWaomqC0qpgCA-OwoO7E71wZyhc31UeIwhhbuVaF5fkWo9AcBGA8Dm0dIXnQWqBtsffg.JmqRaedH43ludNhV4wINykPalvCMpa76_fZVouakFeHdgp1IKcakU_d82lSO9c939OMZsxNRawX-JDzyW-I7DJnlXUiB3gCtvcR6VA) (2016) with Christopher Blattman, Julian Jamison, and Jeannie Annan, *Global Mental Health* ([surveys, data, and full replication materials](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/QA0R1O))

* [Women’s entrepreneurship and intimate partner violence: A cluster randomized trial of microenterprise assistance and partner participation in post-conflict Uganda](https://www.researchgate.net/profile/Eric_Green5/publication/275046325_Women%27s_entrepreneurship_and_intimate_partner_violence_A_cluster_randomized_trial_of_microenterprise_assistance_and_partner_participation_in_post-conflict_Uganda_SSM-D-14-01580R1/links/5a121a430f7e9bd1b2c10035/Womens-entrepreneurship-and-intimate-partner-violence-A-cluster-randomized-trial-of-microenterprise-assistance-and-partner-participation-in-post-conflict-Uganda-SSM-D-14-01580R1.pdf?origin=publication_detail&ev=pub_int_prw_xdl&msrp=svrD-azNiDk00uzI5mO08ly2JmI2-AZ-Xnl4QucHhXjeCoYi5-bVngHPtIiMZd4oOq6d8ukRhmceEb7VMD5p0RGFi4_8Nsu9pOulfhSvTKugydZYcTjg4Gka.83YIbJMHHADIGNb-Wy80ywPbIcoQ8wtn7EvfxdqN-JDz60nSdYrPy9D5AlqBhYRlJ3DvTeN9lhE59dVVYYjHv8BlMLrfbxKk3AHJhA.yQinGWvNPusitrMOomIGKuQd07tZk5u_55GkdnjFN0TrhH23XFBCa0zbu7hDapIPk9s4Xd8WGErW0qPoPrnJpINCOK5EfK-0Z7tFFQ.fbUMCS8x3a8N4hwG3Vd83QxtqeuAL-Y0S0RLb3le7pRRItgCvL_7PzrE4FkL3vhdZu0Id3Y6MFvL7MXJl9YWYttyllwgf6HlgpoA2Q) (2015) with Christopher Blattman, Julian Jamison, and Jeannie Annan, *Social Science & Medicine* ([surveys, data, and full replication materials](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/QA0R1O))

* [Promoting recovery after war in northern Uganda: Reducing daily stressors by alleviating poverty](https://www.researchgate.net/profile/Eric_Green5/publication/271754226_Promoting_Recovery_After_War_in_Northern_Uganda_Reducing_Daily_Stressors_by_Alleviating_Poverty/links/570cd66108aec783ddcd2cc2/Promoting-Recovery-After-War-in-Northern-Uganda-Reducing-Daily-Stressors-by-Alleviating-Poverty.pdf?_iepl%5BhomeFeedViewId%5D=BPnLMGN1L6B8aVZP81Khb8qNC571CjAzJ2JN&_iepl%5Bcontexts%5D%5B0%5D=pcfhf&_iepl%5BinteractionType%5D=publicationDownload&origin=publication_detail&ev=pub_int_prw_xdl&msrp=Q2r4Ur9tbNuXhPNfA1x22FzcFE4nMaub1FleaVuk0TTNwI_gkTew1ygpW1DdFdE_sOVIHIh43mCAkSinnGra-I3vg9DmxzHPzdx5b1Kq9g44EFQtfcGlD3bi.6J0HGEh_JNQmGHEge4Ln0qjdHZxZV1CWwLW6Gw5eZyIq6nfDweI0J6FdF1VByPTOXb6s47WQoHHn2Dt8yEcYKYWxRNFZrUuaiWWYTQ.7l_wbdZd_OFb7pDp49NojkKzBU_CQE9mOxTfWFmuy_zUG5mQd_64V1QHT2o-YKAHnc56Fg8KV9m4P0ZiBmBXdPPt76mRW5NH4w1Qdw.XPR1H0AHpfZd2VN55ofD2tlnC8KYPJoZOnKGmBS5CBSAmklhuZT-AGpTFzd1R0S3oXQGWuE7r5qfHcsGn4H8yv9Afiul33xFEBLeOQ) (2013) with Jeannie Annan and Moriah Brier, *Journal of Child & Adolescent Trauma*

# Family-Based Interventions

Most kids grow up in family systems, so promoting child development, health, and well-being means engaging families in prevention and treatment. Family-based work presents some interesting methodological and implementation challenges, however. How do you measure constructs like family functioning and child maltreatment? What is the best way to rigorously evaluate complex interventions? I've had the opportunity to explore these issues in Kenya and Liberia through a collaboration with [Eve Puffer](http://globalhealth.duke.edu/people/faculty/puffer-eve). She heads a research team that develops and tests family-based interventions. Some of her work is done in partnership with the [International Rescue Committee](https://www.rescue.org/).

## Parents Make the Difference

* [Impact of the 2014 Ebola virus disease outbreak in Liberia on parent preferences for harsh discipline practices: A quasi-experimental, pre-post design](https://doi.org/10.1017/gmh.2017.24) (2018) with Rhea Chase, John Zayzay, Amy Finnegan, and Eve Puffer, *Global Mental Health*

* [A qualitative study of mechanisms underlying effects of a parenting intervention in rural Liberia](https://www.researchgate.net/profile/Ali_Giusto/publication/319920721_A_Qualitative_Study_of_Mechanisms_Underlying_Effects_of_a_Parenting_Intervention_in_Rural_Liberia/links/5a123f180f7e9bd1b2c10257/A-Qualitative-Study-of-Mechanisms-Underlying-Effects-of-a-Parenting-Intervention-in-Rural-Liberia.pdf?_iepl%5BhomeFeedViewId%5D=766DrFNBhtCx1DxzRY7XDwW0&_iepl%5Bcontexts%5D%5B0%5D=pcfhf&_iepl%5BinteractionType%5D=publicationDownload&origin=publication_detail&ev=pub_int_prw_xdl&msrp=Ixc9CBwVaBQ8hOc8ownpMjgggCEhZ3O7c_WDzBNNgBE48CXGMjgj8hqVlsmlWe0ck2Czozj-qWpuCRUBhEkM2UFUxo_zIF5axkreDJdIbB0uyuTzqsLV4pmU.yqLkLqmF4MQ0kM6v-tVXp88gxdMcBMwTasJNThcyaPb-Cp5GKqtg-MBz4iB6xqk7Omwpy6fdDpb_33cXkMCrItk6jwuBKD3uRccXsQ.Ul_cgyObx5-jzx_gkTuB-PoV7kMUP1kmSlDvPPI2exEdqpiYxBDla4lzFFcgQ3OXi0x4cepM-MsYXjyNum9s_zae2edm0hH23_IoHQ.wlCYlhAYXlkUNKO6AzCI4JYkEUlUrNIYYHlDcHewrflek0eR4yD5yvD01KuyJ_gdrTHRnsm5kr7adIvRe6lMA0pinyqvdj7TvQqcfw) (2017) with Ali Giusto, Elsa Friis, Amanda Sim, Rhea Chase, John Zayzay, and Eve Puffer, *European Journal of Development Research*

* [Parents Make the Difference: A randomized-controlled trial of a parenting intervention in Liberia](https://www.researchgate.net/profile/Eve_Puffer/publication/282553023_Parents_make_the_difference_a_randomized-controlled_trial_of_a_parenting_intervention_in_Liberia/links/563e7b7708ae8d65c01439ae/Parents-make-the-difference-a-randomized-controlled-trial-of-a-parenting-intervention-in-Liberia.pdf?_iepl%5BhomeFeedViewId%5D=CKB0Oqufk509FOBk9Zk0Njn8&_iepl%5Bcontexts%5D%5B0%5D=pcfhf&_iepl%5BinteractionType%5D=publicationDownload&origin=publication_detail&ev=pub_int_prw_xdl&msrp=IhXIv92MLcAi61q4TuHOsCNbn6XoIkAkbGxR6n4enRFYDG_hMAq-GYMtdROXSkKwC3azGk1DyU-DN9RamouLHA87qltU3Wt1nGEtWFxaZepnSylLebs7jiRp.JlhFNfgPCphO2MHLRaw_lZjvocbcNEcvJpgjo0l986UFAy7oItfsoXbhzoqghZFa0xoxIRS4l9eCeVmiej4mQol2ICkp4dG4O7BWsw.pFLHb-WAAQBTACcKYCqwq8Yk3mgiU3j-kfskYtgwRvkmcLOmWub_WHmDZlBEKXbaCqmHR7YjgTzDXqcjzRU946xXQs0lfKXLqlavTQ.emsJEBBT6LZKvX75qwYel7Z9goQEj3jsIuUlX6cxTk-8A45i36oGZxJtse6coPBMs7rNAelx48M1yGce3shioNv3lywK5SVE1tkhKg) (2015) with Eve Puffer, Rhea Chase, Amanda Sim, John Zayzay, Eduardo Garcia-Rolland, and Laura Boone, *Global Mental Health*

## READY

* [Associations between fathers’ and sons’ sexual risk in rural Kenya: The potential for intergenerational transmission](https://www.researchgate.net/profile/Ali_Giusto/publication/315928873_Associations_Between_Fathers%27_and_Sons%27_Sexual_Risk_in_Rural_Kenya_The_Potential_for_Intergenerational_Transmission/links/5a123ff00f7e9bd1b2c10262/Associations-Between-Fathers-and-Sons-Sexual-Risk-in-Rural-Kenya-The-Potential-for-Intergenerational-Transmission.pdf?_iepl%5BhomeFeedViewId%5D=eoJ9erZgaWE7ON0asMo9GGnA&_iepl%5Bcontexts%5D%5B0%5D=pcfhf&_iepl%5BinteractionType%5D=publicationDownload&origin=publication_detail&ev=pub_int_prw_xdl&msrp=FrTR-79FzX4ss8PPVd_1BRRZpsKpgVavPqKLxLDIzPrPCoXwGHXqCBpBrAiX7iULCs8DvQsgTl_w3J_0HTxG-wqYZRv4IwyM52bENb4vC5CPA1MBp6Y0cCTZ.XmYBe-Bg_Rg_FeT-31as8gOzARVCCgrAoNZ3jUwZyn0CtsKBciiLEZbl_bO2W7o4iaJUc3d7wehnPs6evc7IWsKC4QE0e-NZCF5Qsg.E5Irq4laAODZZw_V4oyxIDfAdWKRMxxQhjeDVSt3GTxFcqeVoS77OJbDgxZZWDFCI-DhlSpO4p1DwhMuE8B4_zmcNER7mJ5ZCm_NHA.rT3CCtT18GIUr-wr_Yol6Z9B2j8RxXSHecwTcZvhBNDCfktlvH7Uhau0T8VL7wuBIeW92WRTE90ewbmIBnH5RnANbuHHr9Htt3HTrw) (2017) with Ali Giusto and Eve Puffer, *Journal of Adolescent Health* 

* [A church-based intervention for families to promote mental health and prevent HIV among adolescents in rural Kenya: Results of a randomized pilot trial](https://www.researchgate.net/profile/Eve_Puffer/publication/298798015_A_Church-Based_Intervention_for_Families_to_Promote_Mental_Health_and_Prevent_HIV_Among_Adolescents_in_Rural_Kenya_Results_of_a_Randomized_Trial/links/57216e1d08aea92aff8b2d51/A-Church-Based-Intervention-for-Families-to-Promote-Mental-Health-and-Prevent-HIV-Among-Adolescents-in-Rural-Kenya-Results-of-a-Randomized-Trial.pdf) (2016) with Eve Puffer, Kathleen Sikkema, Rose Ogwang-Odhiambo, and Sherryl Broverman, *Journal of Consulting and Clinical Psychology*

# HIV

I've worked on a number of studies that touch on issues related to HIV prevention and treatment. Most recently, I led a team in Zimbabwe [developing a measure of caregiver readiness to disclose a child's HIV status to the child](https://ericpgreen.github.io/r2d2/) (NICHD 5R21HD076695-03).

* [Participatory mapping in low-resource settings: Three novel methods used to engage Kenyan youth in community-based HIV prevention research](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5517656/) (2016) with Eve Puffer, Virginia Warren, and Sherryl Broverman, *Global Public Health*

* [A clinical decision support system for integrating tuberculosis and HIV care in Kenya: A human-centered design approach](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4149343/) (2014) with Caricia Catalani, Keny Aggrey, Philip Owiti, Lameck Diero, Ada Yueng, Dennis Israelski, and Paul Biondich, *PLoS One*

* [Do clinical decision-support reminders for medical providers improve isoniazid preventative therapy prescription rates among HIV-positive adults?: study protocol for a randomized controlled trial](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4404590/) (2015) with Caricia Catalani, Lameck Diero, Jane Carter, Adrian Gardner, Charity Ndwiga, Keny Aggrey, Philip Owiti, Dennis Israelski, and Paul Biondich

# Forced Migration

As a doctoral student just starting out in global mental health, I spent the better part of 2007 living in northern Uganda and learning about community rebuilding after decades of protracted conflict. 

* [Reconcilable differences? Human diversity, cultural relativity, and sense of community](https://www.researchgate.net/profile/Eric_Green5/publication/47556632_Reconcilable_Differences_Human_Diversity_Cultural_Relativity_and_Sense_of_Community/links/570cd8cb08ae2b772e4257b3/Reconcilable-Differences-Human-Diversity-Cultural-Relativity-and-Sense-of-Community.pdf?origin=fulltextSources_direct) (2011) with Greg Townley, Bret Kloos, and Margarita Franco, *American Journal of Community Psychology*

* [Facilitating youth participation in a context of forced migration: A photovoice project in northern Uganda](https://www.researchgate.net/profile/Eric_Green5/publication/235916533_Facilitating_Youth_Participation_in_a_Context_of_Forced_Migration_A_Photovoice_Project_in_Northern_Uganda/links/570cda3208ae2b772e426fd8/Facilitating-Youth-Participation-in-a-Context-of-Forced-Migration-A-Photovoice-Project-in-Northern-Uganda.pdf?_iepl%5BhomeFeedViewId%5D=WkPxBdMCuMMwgqwtksSDT7De&_iepl%5Bcontexts%5D%5B0%5D=pcfhf&_iepl%5BinteractionType%5D=publicationDownload&origin=publication_detail&ev=pub_int_prw_xdl&msrp=YCcc6u80GSa8MYF04DcxgiZAoV7hsxDgYl7DZ7cCqJOgcZpvZpuYFh-KXNSM00Qyw1k7wyq-p9-FC1B3xo8RZ9HszrET0b1FXe_ljuVYdNYuYZsd2fyxe08k.4UXCyx87jlsN7IMndRkVtmFmnMFQ_Ea0ovBU2Uk-PHcOuUlN1AN0weZoO5dyrxiv9cPhTzd4uuP0iMg1LY6rjZqaXshduNcfVvLpRg.vwL6K7U26nQU9EnjAdL3Ttf4BAG_BR-HBpPkphjP1Zc1klCmyKyoC4PEzSyUx14ETMUomTjlXNpsBtbPyPxmXjLACkXcWpdn5ZUMMw.MbUR02TDAwZgd4cIWSTzvGewXIjmZnhXI0vWXOQA-mt_rJdXPKuD1XkZidy-4RudxUkvgR3ZotnxusO4k1RIpI56ahEmYEIF0YHCQA) (2009) with Bret Kloos, *Journal of Refugee Studies*