---
output:
  html_document:
    toc: true
---

<br>

# Mentoring

I mentor Duke undergraduates and graduate students, primarily those affiliated with the Global Health Institute. We have an [undergraduate major and minor in Global Health](http://globalhealth.duke.edu/education-and-training/undergraduate), and a [Master of Science of Global Health](http://globalhealth.duke.edu/education-and-training/graduate/master-of-science) degree program.

<b>Graduate Students</b>: Every year I take one or two new MSc in Global Health students. Our MSc program has a student-mentor matching process that begins soon after students arrive in the fall. Please contact me early if you have an interest in joining my group. Typically students that I mentor work directly with me and my colleagues on existing studies, either on the main research protocol or a highly related sub-study. I’m unlikely to take on a student who wants to collect original data for a completely independent study. Fieldwork is tough to organize, and I think it’s in the student’s best interest to stick with a plan that has a high probability of success. The goal is to leave the program on-time with at least one publication under your belt.

<b>Undergraduate Students</b>: I mentor undergraduate students through two programs: 

* [Student Research Training](http://globalhealth.duke.edu/education-and-training/undergraduate/student-research-training-program) (SRT): Students apply in October to be part of a team that works together in the Spring semester in preparation for 8-weeks of summer fieldwork.

* [Bass](http://globalhealth.duke.edu/education-and-training/bass-connections): Bass Connections is a university-wide initiative that provides students with greater exposure to inquiry across the disciplines, partnership with fellow students at a variety of stages in their educational career, sustained mentorship in teams, and the chance to experience the intersections of the academy and the broader world.

# Trainees

## Current

* Stephanie Jaffe, Trinity '20
* [Shyam Pradheep](https://www.linkedin.com/in/shyam-pradheep/), Trinity '20
* Phoebe Kiburi, Trinity '20
* [Chaya Bhat](https://www.linkedin.com/in/chaya-bhat/), Trinity '19
* [Anna-Karin Hess](https://www.linkedin.com/in/anna-karin-hess-1362989a/), Trinity '19
* [Lulla Kiwinda](), Trinity '19

## Former

* [Amy Finnegan](https://www.linkedin.com/in/amy-finnegan-717a7915), Sanford PhD '16, Postdoctoral Fellow
* [Arun Augustine](https://www.linkedin.com/in/aaugustine09/), MSc '18
* [Christina Schmidt](https://www.linkedin.com/in/christina-schmidt-9b7674108/), Trinity '17
* [Alex Whitcomb](https://www.linkedin.com/in/alexandra-whitcomb-547720a2/), MSc '17
* [Hawa Tuli](https://www.linkedin.com/in/hawatuli), MSc '16
* [Yujung Choi](https://www.linkedin.com/in/yujung-choi-a5749438/), MSc '17
* [Kiera Needham](https://www.linkedin.com/in/kiera-needham-b7a66b89/), Trinity '18
* [Ishan Thakore](https://www.linkedin.com/in/ishan-thakore-4053938a), Trinity '15
* [Mark Herzog](https://www.linkedin.com/in/mark-herzog-548b7988), Trinity '15
* Amogh Karnik, MSc '13